### ISSUE TITLE
Project list doesn't get saved

### ISSUE THREAD

**Issue by chuwy** [ahmedkhalf/project.nvim#10]
From [what I see](https://github.com/ahmedkhalf/project.nvim/blob/339ea7282ebefacb93c6a3ac36f424d166483e2f/lua/project_nvim/project.lua#L254-L255) all projects should get saved on exit. But I have to re-add projects every time I start Vim.

**Comment by ahmedkhalf** [comment]
Please answer a few questions:
1. Which operating system do you use?
2. Give me the output of the following commands:
   `:lua print(require("project_nvim.utils.path").datapath)`
   `:lua print(require("project_nvim.utils.path").projectpath)`
   `:lua print(require("project_nvim.utils.path").historyfile)`

**Comment by chuwy** [comment]
1. It's macOS Catalina. Also NeoVim is istalled through Nix (0.6.0-dev)
2. Nothing unusual:

```
:lua print(require("project_nvim.utils.path").datapath)
/Users/antonparkhomenko/.local/share/nvim

:lua print(require("project_nvim.utils.path").projectpath)
/Users/antonparkhomenko/.local/share/nvim/project_nvim

:lua print(require("project_nvim.utils.path").historyfile)
/Users/antonparkhomenko/.local/share/nvim/project_nvim/project_history
```

Also if it helps, I tried to add a project into `historyfile`, just a plain path, not sure what the format should be. And after restart this file ends up empty again.

Do you think it could be because of [my fix](https://github.com/ahmedkhalf/project.nvim/pull/6)  in case `-1` also works not as documented? E.g. it could read an empty list every time (from end of the file), and then write that empty file again to the `historyfile`.
