### ISSUE TITLE
How to match an absolute path? Or path with a ~ ?

### ISSUE THREAD

**Issue by myarcana** [ahmedkhalf/project.nvim#109]
I would like to make all of my `~/.config` direct children directories project roots. The obvious pattern `=~/.config/*` didn't work, and then in debugging I discovered that `=~/.config` doesn't work either.

Is there currently a way to do this?

**Comment by ahmedkhalf** [comment]
`>.config`

**Comment by myarcana** [comment]
Won't that also match `~/myproject/.config/data/` ?
