### ISSUE TITLE
[NvimTree] unknown option: update_focused_file.auto_open

### ISSUE THREAD

**Issue by MannyFay** [ahmedkhalf/project.nvim#121]
Why I get this message?

I has implement it in my like in the readme.md:
```
  -- Settings for Project plugin:
  sync_root_with_cwd  = true,
  respect_buf_cwd     = true,
  update_focused_file = {
    enable    = true,
    auto_open = false,
    -- Don't switch automatically the project root:
    update_root = false
  },
```

**Comment by keevan** [comment]
Hi @MannyFay, it seems the option auto_open you have set is not a valid option under the update_focused_file node.

![image](https://github.com/ahmedkhalf/project.nvim/assets/9924643/2cca922c-77a1-4152-9457-153f26534859)

At least from my version of nvim-tree. You may need to tweak this to prevent the option from showing. I couldn't find the auto_open listed in https://github.com/ahmedkhalf/project.nvim/blob/main/README.md, perhaps you are looking at a different document?

**Comment by MannyFay** [comment]
Thanks :) You're right!
