### ISSUE TITLE
How to add a project

### ISSUE THREAD

**Issue by Armadillidiid** [ahmedkhalf/project.nvim#139]
The title says it all. What is the command/keymap to add a current working directory to the project list? This was nowhere specified in the README.

**Comment by lukeberry99** [comment]
Wondering the same thing, I think that it's supposed to add projects automatically if you open directories that contain a `.git` file, but that doesn't work for me (using LazyVim)

**Comment by marcinsydor** [comment]
It's not clear to me as well, the list of projects in Telescope is empty.

**Comment by appelgriebsch** [comment]
This seems to be a bug. Up to recently as soon as you 'chdir' into a directory with a '.git' folder it was added to the project list automatically (for me at least). Now it doesn't do that any longer....

**Comment by goelo** [comment]
wondering the same thing

**Comment by konosubakonoakua** [comment]
```lua
  {
    "ahmedkhalf/project.nvim",
    version = false,
    opts = {
      manual_mode = false, -- automactically add
    },
    event = "VeryLazy",
    config = function(_, opts)
      opts.detection_methods = { "lsp", "pattern" }
      opts.patterns = {
        ".git",
        ".hg",
        ".svn",
      }
      require("project_nvim").setup(opts)
      require("lazyvim.util").on_load("telescope.nvim", function()
        require("telescope").load_extension("projects")
      end)
    end,
    keys = {
      { "<leader>fp", "<Cmd>Telescope projects<CR>", desc = "Projects" },
    },
  },

```

or

`:AddProject`

**Comment by Armadillidiid** [comment]
It works. Thank you @konosubakonoakua
