### ISSUE TITLE
Can't change the rooter 

### ISSUE THREAD

**Issue by anderson-silva-concordia** [ahmedkhalf/project.nvim#14]
I'm trying to set my root directory where there is a .git folder but every time I start a project it goes to wherever lsp sets it.

My config is set as follows

```
  use {
    "ahmedkhalf/project.nvim",
    config = require("project_nvim").setup {
      detection_methods = {"pattern"},
      patterns = {".git"}
    }
  }
```

**Comment by ahmedkhalf** [comment]
Cannot reproduce :(

Could you try adding `silent_chdir = false` and see the message it gives you.

Also does changing your config to this fixes the problem:
```lua
  use {
    "ahmedkhalf/project.nvim",
    config = function()
      require("project_nvim").setup {
        detection_methods = {"pattern"},
        patterns = {".git"}
      }
    end
  }
```

**Comment by anderson-silva-concordia** [comment]
It didn't work! I'm probably just doing something stupid!

The thing is I have a project structure that looks like this:

```
.git
projects/folder-1/package.json
projects/folder-2/package.json
```

So every time I open a file using telescope in the `folder-1` it changes the `cwd` to `projects/folder-1`.

I'm using the `tsserver` lsp.

How can I see the logs generate by `silent_chdir = false`

**Comment by ahmedkhalf** [comment]
> How can I see the logs generate by silent_chdir = false

```lua
  use {
    "ahmedkhalf/project.nvim",
    config = function()
      require("project_nvim").setup {
        detection_methods = {"pattern"},
        patterns = {".git"},
        silent_chdir = false
      }
    end
  }
```

You can see it from `:messages`

![image](https://user-images.githubusercontent.com/36672196/130133512-ad175660-1b50-4f66-9ba0-03148290c234.png)

Also which platform are you using? mac, linux windows?

**Comment by anderson-silva-concordia** [comment]
My config is set but I don't see any messages for some reason.

**Comment by ahmedkhalf** [comment]
Are you sure that the plugin is loaded using `:PackerStatus`

**Comment by anderson-silva-concordia** [comment]
I found the problem! The plugin was loaded but I had vim-rooter as well lost in the middle of some plugins and I didn't see it.
It''s working fine now! Thanks for all your help!
