### ISSUE TITLE
Latest telescope update

### ISSUE THREAD

**Issue by wzzbx** [ahmedkhalf/project.nvim#15]
On latest Telescope update :Telescope projects opens :Telescope builtins. Was working fine before

**Comment by ahmedkhalf** [comment]
Unfortunately, I cannot reproduce this bug on the latest telescope, Did you make sure that the `projects` extension is loaded?

```lua
require('telescope').load_extension('projects')

```

**Comment by ahmedkhalf** [comment]
Closing as stale.
