### ISSUE TITLE
How can I exclude some common directories?

### ISSUE THREAD

**Issue by AllenDang** [ahmedkhalf/project.nvim#17]
How can I exclude some common library pathes like:

```sh
/Users/myname/.rustup/...
/Users/myname/.cargo/...
/users/myname/Gopath/pkg/mod/...
```

I often open files from those directories to view the souce code for installed libraries. They are third party libraries, and soon my project list is filled of lots of them. 

Is there a way to exclude them?

**Comment by vuki656** [comment]
Would also be cool if you could remove entries from the list.

**Comment by ahmedkhalf** [comment]
Let me know if the issue is fixed.
