### ISSUE TITLE
null-ls root_dir

### ISSUE THREAD

**Issue by dsully** [ahmedkhalf/project.nvim#19]
project.nvim doesn't appear to be setting the correct root directory for null-ls.nvim

For example, it's set one level higher than pylsp finds it's (correct) root directory, which is a subdir.

Let me know if I can get you any more information.

**Comment by ahmedkhalf** [comment]
From what I understood it seems that null-ls.nvim is misconfigured to detect one level higher than pylsp. If this is the case, they are two solutions: 
1. Fix null-ls to point to the right directory
2. Add null-ls to the ignore lsp settings when setting up project.nvim:
```lua
  ignore_lsp = {},
```

**Comment by dsully** [comment]
I'm already using `ignore_lsp = { "null-ls.nvim" }` (have also tried just "null-ls"). From :LspInfo

```
Language client log: /Users/dsully/.cache/nvim/lsp.log
  Detected filetype:   python

  2 client(s) attached to this buffer:

  Client: null-ls (id: 1, pid: 5001, bufnr: [1, 1, 1])
  filetypes:       *, python, markdown, sh, c, cpp, cs, java, javascript, javascriptreact, typescript, typescriptreact, vue, svelte, fish, json, go, nginx, css, scss, html, yaml, rust, lua, text
  autostart:       true
  root directory:  /Users/dsully/dev/repo

  Client: pylsp (id: 2, pid: 191, bufnr: [1])
  filetypes:       python
  autostart:       true
  root directory:  /Users/dsully/dev/repo/module
  cmd:             pylsp

  Configured servers list: sumneko_lua, bashls, clangd, cmake, cssls, html, pylsp, jsonls, denols, dockerls, gopls, yamlls, null-ls, sourcekit, graphql
```

```
$ pwd
/Users/dsully/dev/repo/module
```

**Comment by ahmedkhalf** [comment]
To help debug the situation please set `silent_chdir = false` in your setup. This will show a message everytime the CWD is changed as you can see from this picture.

![image](https://user-images.githubusercontent.com/36672196/131969837-720240f3-874a-4342-bc64-4177fbc47d29.png)

If you still can't see the message you can use `:messages`

**Comment by ahmedkhalf** [comment]
Closed as stale.

**Comment by kohane27** [comment]
Hello there. I was facing similar issue. Plase let me provide some pointers.

Basically, in my case, `null-ls` interferes with `project.nvim` to change dir. You need to add `ignore_lsp = { "null-ls" }` like below:

```lua
project_nvim.setup({
  -- debug: get a message when `project.nvim` changes dir
  silent_chdir = false,
  ignore_lsp = { "null-ls" },
})
```

If it still doesn't work, you may go to your `null-ls` set up. For example, I have the following:

```lua
null_ls.setup({
  debug = false,
  sources = sources,
  root_dir = nls_utils.root_pattern(".git"),
})
```

Removing `root_dir = nls_utils.root_pattern(".git")` should help.

Cheers!
