### ISSUE TITLE
Error executing luv callback: bad argument 3 to 'fs_read'

### ISSUE THREAD

**Issue by jonasstr** [ahmedkhalf/project.nvim#2]
Hello, after installing this plugin I get the following error:
```
Error executing luv callback:
.../plugged/project.nvim/lua/project_nvim/utils/history.lua:67: bad argument #3 to 'fs_read' (number expected, got nil)
```
My configuration looks like this:
```lua
require("project_nvim").setup { }
require("telescope").load_extension("projects")
```
I looked at the docs for `fs_read` [here](https://github.com/luvit/luv/blob/master/docs.md#uvfs_readfd-size-offset-callback) and it seems the offset parameter is allowed to be `nil`. 

Could this be a problem with my neovim version? I have the 0.5.0 stable version. 

Maybe you have an idea what the problem is. Thanks!

**Comment by mcepl** [comment]
My configuration is:
```lua
require("project_nvim").setup {
  patterns = { ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json", "patches", ".osc/" },
}
```
and I get the same error (my neovim is [my own build](https://build.opensuse.org/package/show/home:mcepl:neovim/neovim) from https://github.com/neovim/neovim/commit/33b4513b8) whenever I open vim:
```
Error executing luv callback:
...es/start/project.nvim/lua/project_nvim/utils/history.lua:67: bad argument #3 to 'fs_read' (number expected, got nil)
```

**Comment by chuwy** [comment]
Same problem with 0.6.0-dev:

```
:version
NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by antonparkhomenko

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/5i27zk9xnvyszqbqjvrwinm63rigp25f-neovim-unwrapped-master/share/nvim"
```

Tried to run this function isolated and indeed hit the same exception:

```lua
uv.fs_open("/Users/antonparkhomenko/.zshrc", "r", 438, function(_, fd)
  uv.fs_read(fd, 10, nil, function(_, data)
    uv.fs_close(fd, function(_, _)
    end)
  end)
end)
```
