### ISSUE TITLE
Ignore folder inside of Archive folder

### ISSUE THREAD

**Issue by reisnobre** [ahmedkhalf/project.nvim#20]
Hi, sorry to do this as an issue. I couldn't figure out how to do it properly by myself.

I have an Archive folder that I have on my machine that I use as a reference for something but I don't wanna projects inside of this folder to show up on the projects list. Is there a way to remove projects from the list or ignore everything inside of Archive?

**Comment by ahmedkhalf** [comment]
Duplicate of #17
