### ISSUE TITLE
E5108: Error executing lua ...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:194: attempt to yield across C-call boundary

### ISSUE THREAD

**Issue by AllenDang** [ahmedkhalf/project.nvim#21]
Repo steps:
1. Lanuch nvim.
2. `Telescope projects`.
3. Select any project for the first time will result at this error.
`E5108: Error executing lua ...k/packer/start/project.nvim/lua/project_nvim/project.lua:174: Vim(lua):E5108: Error executing lua ...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:194: attempt to yield across C-call boundary`
4. `Telescope projects` and select same project again works normally.

**Comment by ahmedkhalf** [comment]
As this is a git signs bug, that has now been fixed, I will close the issue. Tnx.
