### ISSUE TITLE
Can't make it work when opeining nvim without a file and using alpha-nvim

### ISSUE THREAD

**Issue by rafamadriz** [ahmedkhalf/project.nvim#22]
Hey, I having an issue when opening nvim when without a file:

my config is like this:

```lua
    use {
        "ahmedkhalf/project.nvim",
        event = "BufRead",
        ft = "alpha",
        config = function()
            require("project_nvim").setup {
                detection_methods = { "pattern", "lsp" },
                show_hidden = true, -- show hidden files in telescope
            }
        end,
    }
```

I was previously using vim-startify, and I was loading on `ft= "startify"` to make it work on the startup screen, with startify the above setup was working perfectly fine.  But for some reason this doesn't work with alpha-nvim, at least not initially. After doing `PackerStatus` I can see that project.nvim is already loaded, then after closing the `PackerStatus` window, it works and goes to the root of the project. 

In case you ask, alpha-nvim defines it's startup screen as filetype `alpha`. So it's not a problem of the alpha filetype not existing and hence project.nvim not loading. 

It is a weird behavior because I can see that project.nvim is loaded when doing `PackerStatus` and after closing that window, it works and goes to the root of the project. But it doesn't work before that.

Here's a video:
https://streamable.com/egc520

You can see that I open nvim, and do `pwd` so you can see the current directory and that effectively project.nvim isn't working, then do `PackerStatus` and you can see that project.nvim shows as loaded, and after closing that window and doing `pwd` again, project.nvim works and goes to the root.  

Edit: I also tested by not lazy loading project.nvim at all and it didn't work on the alpha startup screen either. It's basically the same behavior that I have when lazy loading, doesn't work initially but after doing `PackerStatus` it works.

**Comment by goolord** [comment]
https://github.com/ahmedkhalf/project.nvim/blob/21986b90407064d3f20daff3ec241bb8790c8565/lua/project_nvim/project.lua#L203-L219

https://github.com/ahmedkhalf/project.nvim/blob/21986b90407064d3f20daff3ec241bb8790c8565/lua/project_nvim/project.lua#L226-L228

gonna guess that this is the culprit. `alpha-nvim` sets `buftype=nofile`

**Comment by goolord** [comment]
https://github.com/mhinz/vim-startify/blob/3ffa62fbe781b3df20fafa3bd9d710dc99c16a8c/doc/startify.txt#L975 startify intentionally doesn't set `buftype=nofile` for this reason... maybe i'll consider doing the same 🤔

**Comment by rafamadriz** [comment]
> https://github.com/mhinz/vim-startify/blob/3ffa62fbe781b3df20fafa3bd9d710dc99c16a8c/doc/startify.txt#L975 startify intentionally doesn't set `buftype=nofile` for this reason... maybe i'll consider doing the same thinking

okay thanks for the info, closing this now.
