### ISSUE TITLE
Ability to delete projects

### ISSUE THREAD

**Issue by gikari** [ahmedkhalf/project.nvim#25]
Sometimes project.nvim automatically creates wrong projects. For example (Wrong ones are: _, .husky, the /usr prefixed ones, bismuth/bin):

![Screenshot_20210913_181609](https://user-images.githubusercontent.com/14205339/133110437-cfe8ffe5-714f-4c07-ac83-8878b9258413.png)
 
I want to delete those "projects", since they are no valid.

**Comment by ahmedkhalf** [comment]
This feature is already present, please use the `exclude_dirs` options. You can also manually delete projects from the data file located in `:lua print(require("project_nvim.utils.path").historyfile)`

**Comment by gikari** [comment]
Thanks for the tip :+1: , but the ability to delete with the shortcut is nice to have. It would be also cool to see the advice you gave in the readme. Oh, and maybe some predefined list of `exclude_dirs` could be a saver too! Like, I doubt anyone stores their projects in `/usr` or `~/.cargo` :thinking:

**Comment by ahmedkhalf** [comment]
'aight sure, will see if I ever get to make the feature, I'm kinda extremely busy with uni rn.
