### ISSUE TITLE
Pick one project in `Telescope projects` popup empty file picker.

### ISSUE THREAD

**Issue by AllenDang** [ahmedkhalf/project.nvim#3]
I read the same issue from reddit post and I met same one here.

I'm not sure this is a bug for telescope because `telescope-project` extension I was using works well in same case.

**Comment by beauwilliams** [comment]
The problem is you need to hit insert first. We can add a startinsert command and that should solve the issue

**Comment by ahmedkhalf** [comment]
@AllenDang Please let me know if the issue is still present.

**Comment by AllenDang** [comment]
@ahmedkhalf Thanks! It is fixed.
