### ISSUE TITLE
Per project configuration

### ISSUE THREAD

**Issue by MordechaiHadad** [ahmedkhalf/project.nvim#30]
Would be pretty cool to have per project configuration using JSON and if possible also allow other plugins to write extensions for this plugin

**Comment by elken** [comment]
Such functionality is [already possible](https://github.com/neovim/nvim-lspconfig/wiki/Project-local-settings)

**Comment by elken** [comment]
Then I'd suggest reading again. You can do anything.

**Comment by ahmedkhalf** [comment]
That was actually one of the goals I had in mind when first developing project.nvim, unfortunately though it proved to be a big security issue. I am still exploring ways to add that feature while having minimal impact on security, so if u got any ideas l'me know!

**Comment by elken** [comment]
Look at how projectionist does it would be a good start, I would say :)

**Comment by MordechaiHadad** [comment]
> 
> 
> That was actually one of the goals I had in mind when first developing project.nvim, unfortunately though it proved to be a big security issue. I am still exploring ways to add that feature while having minimal impact on security, so if u got any ideas l'me know!

that is good to hear

**Comment by TD-Sky** [comment]
Neovim added `exrc` option at 0.9 but project.nvim hasn't benefited from it. I guess it's because neovim sources exrc during startup instead of opening a new buffer. Would you consider to sourcing the exrc may exist every time jumping to a new project?
