### ISSUE TITLE
Recent projects list is empty & cd doesn't work on macOS

### ISSUE THREAD

**Issue by ecosse3** [ahmedkhalf/project.nvim#32]
Hi,

I am using this plugin on my Linux machine as well also on Macbook but on macOS, it doesn't work. I'm not sure if it's happened because I have null-ls installed too but I think it's related only to OS. Same nvim config between two computers.

`:lua print(vim.inspect(require('project_nvim.utils.history').get_recent_projects()))` gives me empty array {}
I cannot see any projects when I type `:Telescope projects`

`:!pwd` is always the same for a project and it doesn't change the root working directory.

I was thinking that's because of structure I have:

- packages
  - UI
     - package.json
     - .eslintrc.js
   - APP
      - package.json
      - .eslintrc.js
- package.json

Because of that null-ls doesn't work in UI and APP directories because it cannot read config.

Any hints on that? Thank you for such a needed plugin!

NVIM v0.6.0-dev+nightly-882-g93d33ed02
Build type: Release
LuaJIT 2.1.0-beta3
Mac OS X 10.15.7

**Comment by elken** [comment]
Ah unfortunate! Glad it's working now :)
