### ISSUE TITLE
[Bug] Cant map to telescope

### ISSUE THREAD

**Issue by chriztheanvill** [ahmedkhalf/project.nvim#36]
Hi.
I am trying to map the plug but does not work:
nnoremap <leader>fp <cmd>lua require('telescope.builtin').projects( require('telescope.themes').get_dropdown({hidden = true}))<cr>

Always show an error that projects does not exist, but if I try to run :Telescope projects it works.

Edit: Kind of solution:
nnoremap <leader>fp <cmd>Telescope projects<CR>

**Comment by ahmedkhalf** [comment]
project.nvim is not builtin to telescope, it's an extension:
```lua
require('telescope').extensions.projects.projects( require('telescope.themes').get_dropdo
wn({hidden = true}))
```

**Comment by chriztheanvill** [comment]
Thank you, works better with that :D

**Comment by tranvnhan** [comment]
> project.nvim is not builtin to telescope, it's an extension:
> 
> ```lua
> require('telescope').extensions.projects.projects( require('telescope.themes').get_dropdown({hidden = true}))
> ```

I wonder why this is not mentioned on the README file.

For anyone who is looking for a way set the keymap, here's what I did:
```lua
keymap("n", "<leader>fp", "<cmd>lua require('telescope').extensions.projects.projects(require('telescope.themes').get_dropdown({hidden=true}))<cr>", opts) -- find projects

```
