### ISSUE TITLE
null-ls dignostics are not working 

### ISSUE THREAD

**Issue by TheSafdarAwan** [ahmedkhalf/project.nvim#42]
i am using null-ls for formatting and linting i have used the telescope community plugin for the projects it had problems with detecting and right configuration for lsp so i tried this plugin it works great but it has only one problem it does not attaches the null-ls dignostics to the buffer 
![image](https://user-images.githubusercontent.com/87114084/139640811-58517b68-77d3-45af-b65f-99b3eee72fd5.png)
and this is my config file https://github.com/imSafdarAwan/Dnvim/blob/a26ffa81fcff12d8a7388c84ade8d9abcd57e6f6/nvim/.config/nvim/lua/plugins/init.lua#L48

**Comment by ahmedkhalf** [comment]
> it does not attaches the null-ls dignostics to the buffer

Hum, I don't that's a problem with project.nvim though? The only thing project.nvim does is cd into the root of the active lsp servers.

**Comment by pspiagicw** [comment]
@ahmedkhalf is right. This is not the responsibility of `project.nvim`. It does not deal with setting up language servers for projects. That is the responsibility of the LSP frontend you are using (`null-ls` for your case). I think we can close this issue.
