### ISSUE TITLE
Open Telescope with specific theme

### ISSUE THREAD

**Issue by gegoune** [ahmedkhalf/project.nvim#46]
Hey, when opening `:Telescope projects theme=ivy` properly themed window opens, but once project is selected and file finder shows it no longer uses configured theme but default one instead. Is there a way to configure that?

**Comment by gasacchi** [comment]
if you only use one specific theme for all pickers you can configure it in setup function:
```diff
- require'telescope'.setup {}

+ require'telescope'.setup {
+  pickers = {
+   find_files = {
+      theme = "ivy"
+    }
+  }
+}
```

**Comment by gegoune** [comment]
Thanks. I have since moved to custom theme and am no longer experiencing this issue.
