### ISSUE TITLE
How do I add more projects to the list?

### ISSUE THREAD

**Issue by jaime10a** [ahmedkhalf/project.nvim#50]
Im not sure if I have to manually add projects somehow?
But i just installed it and i only managed to get the nvim config project on the Telescope list.
Going to other Folders and doing :ProjectRoot doesnt add other Projects to the List.
Im using nvim 0.6

**Comment by vuki656** [comment]
You have to visit the projects and they will get auto-added. 

I don't think there's a manual way to add them.

**Comment by jaime10a** [comment]
@vuki656 Thanks. Yeah it worked now with other projects for me. I just didnt (and still havent) managed to get a flutter project and my window manager (configuration) added to the list. It would be cool if there was a manual way to add any folder to the project list.

**Comment by vuki656** [comment]
Do those projects have anything that matches the `pattern` in the setup? 

Check [here](https://github.com/ahmedkhalf/project.nvim#%EF%B8%8F-configuration) on how a project is detected

**Comment by jaime10a** [comment]
Ok i just needed to git init those projects and now it works:) Thank you
