### ISSUE TITLE
Issue with Monorepos

### ISSUE THREAD

**Issue by LandonSchropp** [ahmedkhalf/project.nvim#52]
In languages such as JavaScript, it's popular to set up projects with multiple packages in the same repo. With JavaScript, there's typically a root `package.json` file and a `packages` directory containing individual `package.json` files for each package. These files are all contained inside the same Git repo.

Currently, when opening a file contained in a subdirectory, project.nvim automatically switches to the child project. This isn't ideal, because there's no way to switch back to the parent directory.

Ideally, when working with a monorepo, project.nvim will leave the root as the base of the project, and won't switch the working directory to the subdirectories.

To see this behavior in action, you can clone my [yeoman-generators](https://github.com/LandonSchropp/yeoman-generators) repo. If you open a file such as `packages/generator-eslint/app/index.js`, you'll see the working directory change to `packages/generator-eslint`.

**Comment by gegoune** [comment]
From readme:

>  -- All the patterns used to detect root dir, when **"pattern"** is in
>  -- detection_methods
>  patterns = { ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json" },

Change it to your liking. You also might want to update `ignore_lsp` if that's causing project to change `pwd`.

**Comment by LandonSchropp** [comment]
@gegoune Thanks for the quick reply!

I'm not sure if changing the detection method is the problem here. I feel like `package.json` should be used to detect root directories.

Rather, the problem here seems to be the switching behavior in monorepos. If you're inside a parent directory that's a monorepo containing g subdirectories that match a pattern, then I don't think project.nvim should switch into those subdirectories. I feel like monorepos should be considered before switching. Or at least this should be a configuration option. I believe [vim-rooter](https://github.com/airblade/vim-rooter/issues/108) handles this in the way I'm describing.

I'm not sure if `ignore_lsp` solves the issue here.

**Comment by gegoune** [comment]
You are right. Perhaps some go this could help https://github.com/ahmedkhalf/project.nvim#pattern-matching?

**Comment by LandonSchropp** [comment]
That's a good idea! My monorepos currently have this structure:

```
packages
├── generator-babel
│   ├── package.json
│   └── yarn.lock
├── generator-eslint
│   ├── package.json
│   └── yarn.lock
├── generator-import-js
│   ├── package.json
│   └── yarn.lock
└── generator-language-server
    ├── package.json
    └── yarn.lock
```

I was able to get this to work by excluding directories whose parent is `packages`. (I'm using LunarVim, which passes `lvim.builting.project` to the project.nvim `setup` method.)

``` lua
table.insert(lvim.builtin.project.detection_methods, 0, "!>packages")
```

Thanks!

**Comment by datner** [comment]
@LandonSchropp I think you meant
```lua
table.insert(lvim.builtin.project.patterns, 0, "!>packages")
```
since `detection_method` expect _only_ `lsp` or `pattern`

**Comment by LandonSchropp** [comment]
Hey @datner, some time has passed and I'm running into this issue again.

Nowadays, I'm using LazyVim for my config, and I noticed lately that my monorepo settings don't seem to be applied.

Here's my config:

``` lua
-- Automatically change into project root directories.
return {
  "ahmedkhalf/project.nvim",
  opts = {
    -- Display a message when changing the project root.
    silent_chdir = false,

    -- Don't change to child packages in monorepos.
    patterns = { "!>packages" },
  },
  config = function(_, options)
    require("project_nvim").setup(options)
  end,
}
```

Any ideas?
