### ISSUE TITLE
Doesn't work since NVIM v0.7.0-dev+786-g9804a2870

### ISSUE THREAD

**Issue by AllenDang** [ahmedkhalf/project.nvim#53]
Everything works fine with NVIM v0.6.0. After upgrade neovim to v0.7.0-dev+786-g9804a2870, this extension doesn't work anymore.

Here is my neovim version:

```
OS: macOS 12.1

NVIM v0.7.0-dev+786-g9804a2870
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by wolves** [comment]
This appears to be related to underlying plugin changes, within Telescope, that have been resolved. I cannot fully confirm this as I didn't debug it myself but my experience is that after updating Telescope this morning this extension is back to working properly.

Based on the recent Telescope commit log it looks like there were some changes going on with loading extensions that may have temporarily caused issues.

@AllenDang would be interested to know if updating Telescope resolves your issues as well.

**Comment by clement-buchart** [comment]
Can confirm this morning `:Telescope projects` didn't work for me on a nvim 0.6

`:lua require('telescope').extensions.projects.projects()` still worked, which indeed seems to indicate some issue with Telescope

**Comment by AllenDang** [comment]
@wolves Yes, I can open projects, but I met another issue, the file picker doesn't start with insert mode.
Repo steps are:
1. Invoke `Telescope projects`.
2. Type something and press enter.
3. Files picker is shown, but not in insert mode.

**Comment by wolves** [comment]
> @wolves Yes, I can open projects, but I met another issue, the file picker doesn't start with insert mode. Repo steps are:
> 
>     1. Invoke `Telescope projects`.
> 
>     2. Type something and press enter.
> 
>     3. Files picker is shown, but not in insert mode.

I am seeing this as well.
