### ISSUE TITLE
The file picker doesn't start with insert mode with neovim master branch.

### ISSUE THREAD

**Issue by AllenDang** [ahmedkhalf/project.nvim#54]
The file picker doesn't start with insert mode.

Repo steps are:

Invoke Telescope projects.
Type something and press enter.
Files picker is shown, but not in insert mode.

My neovim version is
```
NVIM v0.7.0-dev+792-gc46f7caad
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by jugarpeupv** [comment]
Also, it takes a while to load the files in find files prompt

**Comment by johnmathews** [comment]
How can we make it start in insert mode?
