### ISSUE TITLE
project.nvim auto deletes projects when access is denied

### ISSUE THREAD

**Issue by aleprovencio** [ahmedkhalf/project.nvim#60]
Hello, this is an updated description of this issue after further testing.

I'm a `firejail` user, and I have some use cases for it in which it prevents `neovim` from accessing some directories, like: `neovim` is configured as `qutebrowser`'s editor, but when started from there it has no access permissions to directories that are on the `project.nvim`'s project list.

The problem is that when `project.nvim` is denied access, it will delete that project from the list.

I know there's the possibility of lazy-loading `projects.nvim` or maybe even changing the `neovim`'s command configured in `qutebrowser` to use some sort of stripped down version of `init.lua` where it does not load `projects`.

Maybe, is there a better way to handle events like this?

**Comment by aleprovencio** [comment]
There's actually a clue, this is happening on a git controlled hledger's journal repository. It keeps being randomly deleted from the project list.

**Comment by ahmedkhalf** [comment]
You can change the path where project.nvim will store the project history using the `datapath` option. Perhaps for your specific use case, there is a way to detect when vim is launched from qutebrowser and then change the `datapath`.

-- Lua
use {
  "ahmedkhalf/project.nvim",
  config = function()
  -- if not qutebrowser
    require("project_nvim").setup {
      datapath = `normal data path here`
    }
  -- else (qutebrowser)
    require("project_nvim").setup {
      datapath = `qute browser data path here`
    }
  end
}

**Comment by aleprovencio** [comment]
That is indeed a clever solution I have not thought of, thank you @ahmedkhalf !
