### ISSUE TITLE
[Feature Request] : Add the possibilty to run commands when opening projects.

### ISSUE THREAD

**Issue by akai54** [ahmedkhalf/project.nvim#76]
Hey, I thought this would be nice to have,

Often times, projects will require some command(s) to be run every time you work on them
 - Starting a web server
 - Activating a python virtual environment
 - Or even just fetching and pulling changes.

The plug-in should allow you to define and associated command. 
At the press of a button, the working directory is changed to that of your project and the startup command is executed,
thus significantly simplifying and speeding up some of the most common steps you take every time you open Neovim.

**Comment by technicalpickles** [comment]
I think this is a duplicate of https://github.com/ahmedkhalf/project.nvim/issues/76 ?

**Comment by akai54** [comment]
Yeah you're right, I'll close this one.
