### ISSUE TITLE
<c-d> in Telescope doesn't delete the project.

### ISSUE THREAD

**Issue by vzytoi** [ahmedkhalf/project.nvim#82]
\<c-d> in insert mode or d in normal mode doesn't delete the selected project in Telescope. It prompt `Delete '...' from project list? (Y)es, [N]o:` but if I press `Y` it does nothing. Maybe I haven't understand how it is supposed to work? Here is my configuration.
```
use {
    "ahmedkhalf/project.nvim",
    config = function()
        require("project_nvim").setup()
    end
}
```
```
telescope.load_extension('projects')
```
Thank you for this wanderful project and have a good day!

**Comment by deathmaz** [comment]
@vzytoi was the issue resolved for you? Right now i'm facing similar issue when some projects are get deleted and some not

**Comment by vzytoi** [comment]
> @vzytoi was the issue resolved for you? Right now i'm facing similar issue when some projects are get deleted and some not

Hey! I didn't found a solution to this issue even thought I think that you may found one but I understand what was the problem. If you delete the project in which you currently are, then when you close the Telescope prompt it will recreate it instantly so it look like it wasn't deleted. Depending on what you need a solution could be to use the exclude_dirs field from the setup fonction to prevent projects.nvim to recreate it. Let me know if you are able to find a solution to your needs!
