### ISSUE TITLE
Doesn't work properly with Neovide

### ISSUE THREAD

**Issue by xbladesub** [ahmedkhalf/project.nvim#86]
I don't know is it Neovide problem or this plugin, but using Neovide it doesn't work correctly - projects doesn't recognize by default (everything works perfect using iTerm2)

**Comment by zdog234** [comment]
Hmm, after digging around and testing a bit, it seems like this is a reocurrence of an [old neovide issue](https://github.com/neovide/neovide/issues/501).

I created a [new issue](https://github.com/neovide/neovide/issues/1532) to track that. The details on my end is that `VimLeavePre` hooks aren't running in neovide when I quit with `CMD+Q`, but are when I use `:qa`

**Comment by ahmedkhalf** [comment]
Closing since this is not a project.nvim issue. If it is though, lmk and I'l reopen.

**Comment by aweis89** [comment]
Not sure if this helps anyone, but I got this working in Neovide by setting `manual_mode = true` and using `vim-rooter` to correctly change my directory
