### ISSUE TITLE
Ability to search hidden files inside project after selecting it

### ISSUE THREAD

**Issue by gikari** [ahmedkhalf/project.nvim#9]
[Telescope project](https://github.com/nvim-telescope/telescope-project.nvim#available-setup-settings) plugin has an option to do that:

```lua
require('telescope').setup {
  extensions = {
    project = {
      hidden_files = true -- default: false
  }
}
```

Would be nice to have this here too.

**Comment by jonasstr** [comment]
For me, hidden files are actually shown in the Telescope prompt.

Would it instead be possible to pass an option to do the opposite of that, i.e. hide the . files? Or more generally, add an option to pass arbitrary options to Telescope `find_files` as a Lua table?

**Comment by ahmedkhalf** [comment]
I added a new setup option to show hidden files, please let me know if both ur issues have been fixed.
@gikari @jonasstr

**Comment by jonasstr** [comment]
This seems to be working as expected, thank you!

**Comment by gikari** [comment]
> I added a new setup option to show hidden files, please let me know if both ur issues have been fixed.
> @gikari @jonasstr

I use Lunarvim, where it is a built-in plugin, so she lsp does not show the option you've just added, but setting it anyway works.

**Comment by ahmedkhalf** [comment]
Okay, I will add the option to lunarvim too.
